# Generated by Django 3.2 on 2022-11-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20221125_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date_created']},
        ),
    ]
